#pragma config(Motor,  port2,           LeftMotor,     tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port3,           RightMotor,    tmotorVex393_MC29, openLoop, reversed, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

  while (true)
  {


    motor(RightMotor) = vexRT[Ch3] + vexRT[Ch1];
    motor(LeftMotor) = vexRT[Ch3] - vexRT [Ch1];
}
}
