#pragma config(Motor,  port2,           LeftMotor,     tmotorVex393_MC29, openLoop, reversed, driveLeft)
#pragma config(Motor,  port3,           RightMotor,    tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port5,           TopMotor,      tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//Used for testing *Not for comp. use
task main()
{
 	while(1==1)
	{
		if(vexRT[Btn6U] == 1)
{
			motor[TopMotor] = - 90;
}
		else if(vexRT[Btn6D] == 1)
{
			motor[TopMotor] = + 60;
}
		else
{
    motor[TopMotor] = 0;
}



    motor(RightMotor) = vexRT[Ch3] - vexRT[Ch1];
    motor(LeftMotor) = vexRT[Ch3] + vexRT [Ch1];



}

}
