#pragma config(Motor,  port7,           ClawMotor,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//Used for testing *Not for comp. use
task main()
{

	while(1==1)
{
		if(vexRT[Btn5U] == 1)

			motor(ClawMotor) = -127;

		else if(vexRT[Btn5D] == 1)

			motor(ClawMotor) = 127;

		else

			motor(ClawMotor) = 0;

}

}
