#pragma config(Motor,  port2,           RightMotor,    tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port3,           LeftMotor,     tmotorVex393_MC29, openLoop, reversed, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
motor(LeftMotor) = 127;
motor(RightMotor) = 127;


}
