#pragma config(Motor,  port2,           LeftMotor,     tmotorVex393_MC29, openLoop, reversed, driveLeft)
#pragma config(Motor,  port3,           RightMotor,    tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port5,           TopMotor,      tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(1==1)
	{
		if(vexRT[Btn6U] == 1)
{
			motor[TopMotor] = - 90;
}
		else if(vexRT[Btn6D] == 1)
{
			motor[TopMotor] = + 60;
}
		else
{
    motor[TopMotor] = 0;
}



    motor(RightMotor) = vexRT[Ch3] - vexRT[Ch1];
    motor(LeftMotor) = vexRT[Ch3] + vexRT [Ch1];



}
//The robot moves forward
	motor(LeftMotor) = 127;
	motor(RightMotor) = 127;
	wait1Msec(1400);

//The robot stops
	motor(LeftMotor) = 0;
	motor(RightMotor) = 0;
	wait1Msec(500);

//The robot arm rises
	motor(TopMotor) = 127;
	wait1Msec(250);

//The robot arm stops
	motor(TopMotor) = 0;
	wait1Msec(300);

//The robot drives forward
	motor(LeftMotor) = 127;
	motor(RightMotor) = 127;
	wait1Msec(100);

//The robot stops
	motor(LeftMotor) = 0;
	motor(RightMotor) = 0;
	wait1Msec(100);

//The robot arm lowers
	motor(TopMotor) = -127;
	wait1Msec(250);

//The robot arm stops
	motor(TopMotor) = 127;
	wait1Msec(300);

//The robot drives backward
	motor(TopMotor) = -127;
	motor(LeftMotor) = -127;
	motor(RightMotor) = -127;
	wait1Msec(300);


//The robot stops
	motor(TopMotor) = 0;
	motor(LeftMotor) = 0;
	motor(RightMotor) = 0;
	wait1Msec(200);

}
