#pragma config(Motor,  port2,           RightMotor,    tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port3,           LeftMotor,     tmotorVex393_MC29, openLoop, reversed, driveLeft)
#pragma config(Motor,  port7,           ClawMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           TopMotor,      tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
//The robot moves forward *Timing to be determined *detrmine power
	motor(LeftMotor) = 127;
	motor(RightMotor) = 127;
	wait1Msec(2000);

//The robot stops
	motor(LeftMotor) = 0;
	motor(RightMotor) = 0;
	wait1Msec(500);

//The robots claw opens *Timing to be determined *determine power
	motor(ClawMotor) = 127;
	wait1Msec(500);

//The robot stops
	motor(ClawMotor) = 0;
	wait1Msec(1000);

//The robot claw closes *Timing to be determined *Determine power
	motor(ClawMotor) = -127;
	wait1Msec(1000);

//The robot stops
	motor(ClawMotor) = 0;
	wait1Msec(1000);

//The robot arm rises
	motor(TopMotor) = 127;
	wait1Msec(300);

//The robot arm stops
	motor(TopMotor) = 0;
	wait1Msec(500);

//The robot turns 180 degrees *Timing to be determined *Determine power
	motor(LeftMotor) = 127;
	motor(RightMotor) = -127;
	wait1Msec(2000);

//The robot moves forward *Timing to be determined *detrmine power
	motor(LeftMotor) = 127;
	motor(RightMotor) = 127;
	wait1Msec(2000);

//The robot stops
	motor(LeftMotor) = 0;
	motor(RightMotor) = 0;
	wait1Msec(500);

}
