#pragma config(Motor,  port2,           RightMotor,    tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port3,           LeftMotor,     tmotorVex393_MC29, openLoop, reversed, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
//Drive forward
 motor(LeftMotor) = 127;
 motor(RightMotor) = 127;
 wait1Msec(4500);

//Stop
 motor(LeftMotor) = 0;
 motor(RightMotor) = 0;
 wait1Msec(3000);



}
