#pragma config(Motor,  port2,           RightMotor,    tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port3,           LeftMotor,     tmotorVex393_MC29, openLoop, reversed, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//Created for testing *not for comp. use
task main()
{
	//Drives forward and hits the oposing teams mobile goal
		motor(LeftMotor) = 127;
		motor(RightMotor) = 127;
		wait1Msec(?);

	//The robot stops
		motor(LeftMotor) = 0;
		motor(RightMotor) = 0;
		motor(200);

	//The robot turns 90 degrees
		motor(LeftMotor) = -127;
		motor(RightMotor) = 127;
		wait1Msec(500);

	//The robot stops
		motor(LeftMotor) = 0;
		motor(RightMotor) = 0;
		wait1Msec(200);

	//The robot drives forward, nocking over cones
		motor(LeftMotor) = 127;
		motor(RightMotor) = 127;
		wait1Msec(?);

	//The robot stops
		motor(LeftMotor) = 0;
		motor(RightMotor) = 0;
		wait1Msec(200);





	}
